repos:
- repo: local
  hooks:
    - id: python-fastapi-asyncpg-lint-pytest
      name: Run linter and pytest for python-fastapi-asyncpg
      entry: bash -c 'cd python-fastapi-asyncpg/ && make pre-commit'
      language: system
      pass_filenames: false
    - id: golang-gin-pgx-formatter-tests
      name: Run formatter and tests for golang-gin-pgx
      entry: bash -c 'cd golang-gin-pgx/ && make format && make test'
      language: system
      pass_filenames: false
