services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/example_db
      DEBUG: "true"
      JSON_LOGGING: "false"
    ports:
      - "8000:8000"

  db:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d example_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    ports:
      - 8080:8080

  test-runner:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    command: ["make", "lint", "pytest"]

volumes:
  db_data:
