openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /user:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
components:
  schemas:
    UserCreate:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer
      required:
        - name
    UserResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
