[project]
name = "uv_example"
version = "0.1.0"
description = "uv_example"
requires-python = ">=3.13"

dependencies = [
    "fastapi",
    "uvicorn",
]

[project.optional-dependencies]
dev = ["pytest", "black"]
