# generated by datamodel-codegen:
#   filename:  openapi-schema.yaml
#   timestamp: 2025-07-28T11:23:34+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict
from uuid import UUID

from pydantic import BaseModel, Field


class PingResponse(BaseModel):
    message: str = Field(..., example="pong")


class Item(BaseModel):
    id: int = Field(..., example=1)
    uuid: UUID = Field(..., example="550e8400-e29b-41d4-a716-446655440000")
    created_at: datetime = Field(..., example="2021-01-01T00:00:00.000Z")
    name: str = Field(..., example="foo")
    price: float = Field(..., example=3.14)


class ItemIn(BaseModel):
    name: str = Field(..., example="foo")
    price: float = Field(..., example=3.14, ge=0.0)


class GetItemResponse(BaseModel):
    data: Item
    meta: Dict[str, Any]


class CreateItemRequest(BaseModel):
    data: ItemIn


class CreateItemResponseMeta(BaseModel):
    created: bool


class CreateItemResponse(BaseModel):
    data: Item
    meta: CreateItemResponseMeta


class ErrorResponse(BaseModel):
    error: str
