# generated by datamodel-codegen:
#   filename:  openapi-schema.yaml
#   timestamp: 2025-07-28T09:38:09+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class UserCreate(BaseModel):
    name: str
    age: Optional[int] = None


class UserResponse(BaseModel):
    id: Optional[str] = None
    name: Optional[str] = None
    age: Optional[int] = None
