// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ItemsAllGet implements GET /items/all operation.
//
// Returns all Items.
//
// GET /items/all
func (UnimplementedHandler) ItemsAllGet(ctx context.Context, params ItemsAllGetParams) (r *GetItemsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ItemsGet implements GET /items operation.
//
// Returns Items by ids. Only returns subset of Items found.
//
// GET /items
func (UnimplementedHandler) ItemsGet(ctx context.Context, params ItemsGetParams) (r *GetItemsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ItemsIDGet implements GET /items/{id} operation.
//
// Returns Item by id.
//
// GET /items/{id}
func (UnimplementedHandler) ItemsIDGet(ctx context.Context, params ItemsIDGetParams) (r *GetItemResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ItemsPost implements POST /items operation.
//
// Creates Item.
//
// POST /items
func (UnimplementedHandler) ItemsPost(ctx context.Context, req *CreateItemRequest) (r *CreateItemResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// PingGet implements GET /ping operation.
//
// Check if the service is running.
//
// GET /ping
func (UnimplementedHandler) PingGet(ctx context.Context) (r *PingGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
