// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateItem implements createItem operation.
//
// Creates Item.
//
// POST /items
func (UnimplementedHandler) CreateItem(ctx context.Context, req *CreateItemRequest) (r CreateItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetAllItems implements getAllItems operation.
//
// Returns all Items.
//
// GET /items/all
func (UnimplementedHandler) GetAllItems(ctx context.Context, params GetAllItemsParams) (r GetAllItemsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetItem implements getItem operation.
//
// Returns Item by id.
//
// GET /items/{id}
func (UnimplementedHandler) GetItem(ctx context.Context, params GetItemParams) (r GetItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetItems implements getItems operation.
//
// Returns Items by ids. Only returns subset of Items found.
//
// GET /items
func (UnimplementedHandler) GetItems(ctx context.Context, params GetItemsParams) (r GetItemsRes, _ error) {
	return r, ht.ErrNotImplemented
}
