// Code generated by ogen, DO NOT EDIT.
package ogen

type CreateItemRes interface {
	createItemRes()
}

type GetAllItemsRes interface {
	getAllItemsRes()
}

type GetItemRes interface {
	getItemRes()
}

type GetItemsRes interface {
	getItemsRes()
}
