// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateItemOperation  OperationName = "CreateItem"
	GetAllItemsOperation OperationName = "GetAllItems"
	GetItemOperation     OperationName = "GetItem"
	GetItemsOperation    OperationName = "GetItems"
)
