// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteItemParams is parameters of deleteItem operation.
type DeleteItemParams struct {
	// Item ID.
	ItemId int
}

func unpackDeleteItemParams(packed middleware.Parameters) (params DeleteItemParams) {
	{
		key := middleware.ParameterKey{
			Name: "itemId",
			In:   "path",
		}
		params.ItemId = packed[key].(int)
	}
	return params
}

func decodeDeleteItemParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteItemParams, _ error) {
	// Decode path: itemId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "itemId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ItemId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "itemId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetItemParams is parameters of getItem operation.
type GetItemParams struct {
	// Item ID.
	ItemId int
}

func unpackGetItemParams(packed middleware.Parameters) (params GetItemParams) {
	{
		key := middleware.ParameterKey{
			Name: "itemId",
			In:   "path",
		}
		params.ItemId = packed[key].(int)
	}
	return params
}

func decodeGetItemParams(args [1]string, argsEscaped bool, r *http.Request) (params GetItemParams, _ error) {
	// Decode path: itemId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "itemId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ItemId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "itemId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateItemParams is parameters of updateItem operation.
type UpdateItemParams struct {
	// Item ID.
	ItemId int
}

func unpackUpdateItemParams(packed middleware.Parameters) (params UpdateItemParams) {
	{
		key := middleware.ParameterKey{
			Name: "itemId",
			In:   "path",
		}
		params.ItemId = packed[key].(int)
	}
	return params
}

func decodeUpdateItemParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateItemParams, _ error) {
	// Decode path: itemId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "itemId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ItemId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "itemId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
