// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateItem implements createItem operation.
//
// Creates Item.
//
// POST /items
func (UnimplementedHandler) CreateItem(ctx context.Context, req *ItemCreateRequest) (r CreateItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteItem implements deleteItem operation.
//
// Deletes Item.
//
// DELETE /items/{itemId}
func (UnimplementedHandler) DeleteItem(ctx context.Context, params DeleteItemParams) (r DeleteItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetItem implements getItem operation.
//
// Returns a single Item by id.
//
// GET /items/{itemId}
func (UnimplementedHandler) GetItem(ctx context.Context, params GetItemParams) (r GetItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Ping implements ping operation.
//
// Check if the service is running.
//
// GET /ping
func (UnimplementedHandler) Ping(ctx context.Context) (r *PingResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateItem implements updateItem operation.
//
// Updates a single Item by id.
//
// PATCH /items/{itemId}
func (UnimplementedHandler) UpdateItem(ctx context.Context, req *ItemUpdateRequest, params UpdateItemParams) (r UpdateItemRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
