// Code generated by ogen, DO NOT EDIT.
package ogen

type CreateItemRes interface {
	createItemRes()
}

type DeleteItemRes interface {
	deleteItemRes()
}

type GetItemRes interface {
	getItemRes()
}

type UpdateItemRes interface {
	updateItemRes()
}
