// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateItem implements createItem operation.
	//
	// Creates Item.
	//
	// POST /items
	CreateItem(ctx context.Context, req *ItemCreateRequest) (CreateItemRes, error)
	// DeleteItem implements deleteItem operation.
	//
	// Deletes Item.
	//
	// DELETE /items/{itemId}
	DeleteItem(ctx context.Context, params DeleteItemParams) (DeleteItemRes, error)
	// GetItem implements getItem operation.
	//
	// Returns a single Item by id.
	//
	// GET /items/{itemId}
	GetItem(ctx context.Context, params GetItemParams) (GetItemRes, error)
	// Ping implements ping operation.
	//
	// Check if the service is running.
	//
	// GET /ping
	Ping(ctx context.Context) (*PingResponse, error)
	// UpdateItem implements updateItem operation.
	//
	// Updates a single Item by id.
	//
	// PATCH /items/{itemId}
	UpdateItem(ctx context.Context, req *ItemUpdateRequest, params UpdateItemParams) (UpdateItemRes, error)
	// NewError creates *ErrorResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorResponseStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
