// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	ItemsAllGetOperation OperationName = "ItemsAllGet"
	ItemsGetOperation    OperationName = "ItemsGet"
	ItemsIDGetOperation  OperationName = "ItemsIDGet"
	ItemsPostOperation   OperationName = "ItemsPost"
	PingGetOperation     OperationName = "PingGet"
)
