// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateItemOperation OperationName = "CreateItem"
	DeleteItemOperation OperationName = "DeleteItem"
	GetItemOperation    OperationName = "GetItem"
	PingOperation       OperationName = "Ping"
	UpdateItemOperation OperationName = "UpdateItem"
)
