services:
  api:
    container_name: jobqueue-api
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network

  worker:
    container_name: jobqueue-worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    networks:
      - app-network

  redis:
    container_name: jobqueue-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  redis-commander:
    container_name: jobqueue-redis-commander
    image: rediscommander/redis-commander:latest
    platform: linux/amd64  # Force AMD64 platform
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
