[project]
name = "python-fastapi-redisjobqueue"
version = "0.1.0"
description = "FastAPI Redis Job Queue Example"
requires-python = ">=3.13"

dependencies = [
    "fastapi",
    "uvicorn",
    "redis",
    "requests",
    "fire",
]

[project.optional-dependencies]
dev = ["pytest", "black"]
