services:
  app:
    build:
      context: .
    # depends_on:
    #   db:
    #     condition: service_healthy
    environment:
      DEBUG: "true"
      DATABASE_URL: postgresql://user:password@db:5432/example_db
      PORT: "8000"
    ports:
      - "8000:8000"
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: .
    #       ignore:
    #         - .git/
  
  # db:
  #   image: postgres:15.3-alpine3.18
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=example_db
  #   volumes:
  #     - db_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: [ "CMD-SHELL", "pg_isready -U user -d example_db" ]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   ports:
  #     - "5433:5432"

  # migrate:
  #   image: migrate/migrate
  #   volumes:
  #     - ./migrations:/migrations
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   command: ["-path", "/migrations", "-database", "postgres://user:password@db:5432/example_db?sslmode=disable", "up"]
  #   restart: on-failure

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db

volumes:
  db_data:
