openapi: 3.0.3
info:
  title: Items API
  description: A simple CRUD API for items
  version: 1.0.0
servers:
  - url: /api
paths:
  /items:
    get:
      summary: Get Items
      description: Returns Items by ids. Only returns subset of Items found.
      operationId: getItems
      parameters:
        - name: item_ids
          in: query
          description: Item IDs
          required: true
          schema:
            type: array
            items:
              type: integer
          style: form
          explode: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetItemsResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create Item
      description: Creates Item.
      operationId: createItem
      requestBody:
        description: Create Item Request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateItemRequest'
      responses:
        '201':
          description: Item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateItemResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Item already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /items/all:
    get:
      summary: Get All Items
      description: Returns all Items.
      operationId: getAllItems
      parameters:
        - name: offset
          in: query
          description: Offset
          required: true
          schema:
            type: integer
            minimum: 0
        - name: chunkSize
          in: query
          description: Chunk size
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 20
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetItemsResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /items/{id}:
    get:
      summary: Get Item
      description: Returns Item by id.
      operationId: getItem
      parameters:
        - name: id
          in: path
          description: Item ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetItemResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Item not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        uuid:
          type: string
          format: uuid
          example: 550e8400-e29b-41d4-a716-446655440000
        created_at:
          type: string
          format: date-time
          example: 2021-01-01T00:00:00.000Z
        name:
          type: string
          example: foo
        price:
          type: number
          format: float
          example: 3.14
      required:
        - id
        - uuid
        - created_at
        - name
        - price
    ItemIn:
      type: object
      properties:
        name:
          type: string
          example: foo
        price:
          type: number
          format: float
          example: 3.14
          minimum: 0
      required:
        - name
        - price
    GetItemResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Item'
        meta:
          type: object
      required:
        - data
        - meta
    GetItemsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        meta:
          type: object
      required:
        - data
        - meta
    CreateItemRequest:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/ItemIn'
      required:
        - data
    CreateItemResponseMeta:
      type: object
      properties:
        created:
          type: boolean
      required:
        - created
    CreateItemResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Item'
        meta:
          $ref: '#/components/schemas/CreateItemResponseMeta'
      required:
        - data
        - meta
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
      required:
        - error 